version: "2.3"
services:
  gsc:
    build:
      context: .
      args:
        uid: ${uid}
    volumes:
      - type: bind
        source: ./server_files
        target: /home/gsc/server_files
    env_file:
      - vars.env
    stdin_open: true
    tty: true
    
